# permissions for end users to view csnodedaemons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: casimir-operator
    app.kubernetes.io/managed-by: kustomize
  name: csnodedaemon-viewer-role
rules:
- apiGroups:
  - operator.leryn.io
  resources:
  - csnodedaemons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.leryn.io
  resources:
  - csnodedaemons/status
  verbs:
  - get
