---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - operator.leryn.io
  resources:
  - csnodedaemons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.leryn.io
  resources:
  - csnodedaemons/finalizers
  verbs:
  - update
- apiGroups:
  - operator.leryn.io
  resources:
  - csnodedaemons/status
  verbs:
  - get
  - patch
  - update
