apiVersion: operator.leryn.io/v1alpha1
kind: CsNodeDaemon
metadata:
  labels:
    app.kubernetes.io/name: casimir-operator
    app.kubernetes.io/managed-by: kustomize
  name: csnodedaemon-sample
spec:
  # TODO(user): Add fields here
